project_id = "guiifplvaecwbtqtyltk"

[functions.manage-consultora-access]
verify_jwt = false

[functions.create-empresa]
verify_jwt = false

[functions.save-integration-key]
verify_jwt = false

[functions.ai-coach]
verify_jwt = false