project_id = "guiifplvaecwbtqtyltk"

[functions.manage-consultora-access]
verify_jwt = false

[functions.create-empresa]
verify_jwt = false

[functions.save-integration-key]
verify_jwt = false

[functions.ai-coach]
verify_jwt = false

[functions.audit-log]
verify_jwt = false

[functions.admin-empresa-details]
verify_jwt = false

[functions.list-users-admin]
verify_jwt = false

[functions.impersonate-user]
verify_jwt = false

[functions.reprocessar-upload]
verify_jwt = false

[functions.ai-analista]
verify_jwt = false

[functions.send-analise-email]
verify_jwt = false

[functions.validate-resend-key]
verify_jwt = false

[functions.create-user-admin]
verify_jwt = false

[functions.upload-devedores]
verify_jwt = false